### ISSUE TITLE
Sweet!!

### ISSUE THREAD

**Issue by it33** [tjtoml/mattermost-ansible#11]
Hey Tyler, 

Really nice work! 

Would you be up for [sharing some info on your project so we can promote it?](https://www.mattermost.org/share-your-mattermost-projects/)  

Also, would love to have you hang out with the Mattermost community on our server, if you're not there already. We have an [installers and images](https://pre-release.mattermost.com/core/channels/installers-and-images) where we can intro you to other folks doing great work like yours!

Ian

**Comment by tjtoml** [comment]
Done, thanks for reaching out!
