### ISSUE TITLE
Upcoming breaking change when using Mattermost with a reverse proxy

### ISSUE THREAD

**Issue by jasonblais** [tjtoml/mattermost-ansible#17]
My name is Jason Blais and I'm a product manager for the Mattermost open source project.

Mattermost is moving to new APIv4 endpoints, which will allow for more powerful integrations and server interaction.

As part of this move, we will be moving the WebSocket endpoint to APIv4 in Q3 of 2017 (tentatively scheduled for July 16, 2017 release). This will result in a breaking change for deployments using a reverse proxy.

For those configuring NGINX proxy, just a single one-line change is required, replacing the `location /api/v3/users/websocket {` line with `location ~ /api/v[0-9]+/(users/)?websocket$ {` in the `/etc/nginx/sites-available/mattermost` NGINX configuration file. [We've noted this in our documentation](https://docs.mattermost.com/install/install-ubuntu-1404.html#configuring-nginx-as-a-proxy-for-mattermost-server).

I'm opening an issue so we can discuss if any changes are needed for the Ansible package, as we weren't sure what kind of configuration is recommended on your end.

**Comment by tjtoml** [comment]
Jason, 
Is this still scheduled for release on the 16th?

**Comment by jasonblais** [comment]
Yes, this will be on the July 16th release

**Comment by jasonblais** [comment]
If you have any questions about it, don't hesitate to let me know.

**Comment by tjtoml** [comment]
Do you have a version number / download URL for the upcoming release so I can begin testing?

**Comment by jasonblais** [comment]
Not yet --- we're still testing it out actually but hoping to have the final download links available soon.

We'll post them at https://about.mattermost.com/download/ as soon as they're available.

**Comment by jasonblais** [comment]
@tjtoml 

Download links for 4.0.0 are available here: https://about.mattermost.com/download/

Changelog is available here: https://docs.mattermost.com/administration/changelog.html#release-v4-0-0

**Comment by tjtoml** [comment]
Just updated to fix this.

**Comment by jasonblais** [comment]
Awesome, thanks Tyler!! Great work
