### ISSUE TITLE
Maintener Wanted

### ISSUE THREAD

**Issue by luclis** [tjtoml/mattermost-ansible#28]
Hi there, 

I've got some spare time so I can manage your repository as you requested. You've got somes pretty awesome PR like #26 and I'ld be gratefull to include them in Master. 

Best Regards, 
Luclis.

**Comment by tjtoml** [comment]
Sorry dude! I feel bad that I haven't been keeping up with this repo over the years. I've invited you to become a collaborator on this project.

**Comment by luclis** [comment]
Hi ! 
It's okay, i've got some spare time right now, I'll make a little cleanup then upgrade it to the new mattermost version :) 
I'll keep the ALL-IN-ONE logic you made first and precise there is an role-based repository. 
Will you keep maintain your role-base repo ? Did you need some help for them too ? 

Best Regards, 
Luclis
